# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 412fa4d0c88db8e51c7aad2fff046286fbbedd161e832c80bb822b0ec4d3df21a7480afe95dd32d224d6209101eb018daef3b2ca10cbe17c6a64c470599b64e8

test:
  secret_key_base: 0985212e4e84ae9e965009d38b6dacaf83bf1e784d00f7cf010968c2f013a260f5ad637463a06add1fcc62689bdc95e23bec90a79985ccd60ffa4f8d567d1a15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
